[debug] > Exec(~~~run, None, None)
[info] sbt server started at local:sbt-server-d8fb580729e93f09a2f5
[debug] Writing bsp connection file
[info] started sbt server
[debug] > Exec(__runWatch console0, None, None)
[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(__preWatch console0, None, None)
[debug] > Exec(~~run, None, None)
[error] java.lang.IllegalStateException: Tried to start new watch while channel, 'console0', was already watching '~~run'
[error] 	at sbt.internal.ContinuousCommands$.$anonfun$setupWatchState$1(Continuous.scala:1291)
[error] 	at sbt.internal.ContinuousCommands$.$anonfun$setupWatchState$1$adapted(Continuous.scala:1215)
[error] 	at sbt.internal.Continuous$.$anonfun$continuous$1(Continuous.scala:120)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:151)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:146)
[error] 	at sbt.Command$.process(Command.scala:194)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$7(MainLoop.scala:267)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:267)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:312)
[error] 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:171)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:290)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:326)
[error] 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:171)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:171)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:152)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:127)
[error] 	at sbt.io.Using.apply(Using.scala:28)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:120)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:74)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:50)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:225)
[error] 	at sbt.xMain$.$anonfun$run$11(Main.scala:135)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withIn(Console.scala:230)
[error] 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:610)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:390)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:600)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withErr(Console.scala:196)
[error] 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:600)
[error] 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:390)
[error] 	at sbt.xMain$.withStreams$1(Main.scala:88)
[error] 	at sbt.xMain$.run(Main.scala:123)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
[error] 	at sbt.xMain.run(Main.scala:47)
[error] 	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:149)
[error] 	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:159)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:44)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:21)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
[error] 	at xsbt.boot.Boot$.run(Boot.scala:73)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:21)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalStateException: Tried to start new watch while channel, 'console0', was already watching '~~run'
[error] Use 'last' for the full log.
[debug] > Exec(resumeFromFailure, None, None)
[debug] > Exec(sbtPopOnFailure, None, None)
[debug] > Exec(__postWatch console0, None, None)
[debug] > Exec(__waitWatch console0, None, None)
